FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache bash curl unzip && curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:$PATH"

COPY package.json bun.lock ./
RUN bun install

CMD ["bun", "run", "dev", "--host", "0.0.0.0"]
